<PittodoMain>:

    Label:
        font_size: 20
        right: root.width - 10
        top: 70
        text: "PittodoMain"


    Button:
        text: 'add_task()'
        on_press: app.add_task()
        on_release: app.model.add_task()
        # on_state:
            # print("my current state is {}".format(self.state))
        height: 50
        width: 100
        top: root.top - 10
        x: 10
